import { cp, readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { claude } from "../src/adapters/claude.ts";
import type { ImportResult } from "../src/adapters/types.ts";
import { layerDirs, parseLayers } from "../src/ir/parse.ts";
import type { Scope } from "../src/ir/schema.ts";
import { layerFiles } from "../src/ir/serialize.ts";
import { compile } from "../src/sync/compile.ts";
import { writeArtifact, writeAtomic } from "../src/sync/write.ts";
import { FIXTURES, writeTree } from "./helpers.ts";

async function sync(root: string, home: string, scopes: Scope[]) {
  const layers = await parseLayers(root, home);
  const { compiled } = await compile(claude, layers, scopes, root, home);
  for (const c of compiled) for (const a of c.artifacts) await writeArtifact(a);
  return compiled;
}

const importScope = (root: string, home: string, scope: Scope) =>
  claude.import(root, { scope, root, home });

/** The `.agents/` side of the round-trip: what `init --import` writes. */
async function init(root: string, home: string, scope: Scope, imported: ImportResult) {
  const files = layerFiles(layerDirs(root, home)[scope], imported);
  for (const [path, content] of Object.entries(files)) await writeAtomic(path, content);
}

const withoutSources = (r: ImportResult) => ({
  ...r,
  instructions: r.instructions.map(({ scope, body }) => ({ scope, body })),
});

describe("round-trip: existing global Claude config (acceptance)", async () => {
  const home = await writeTree({});
  await cp(join(FIXTURES, "claude-global/home"), home, { recursive: true });
  const root = await writeTree({});
  const originalMd = await readFile(join(home, ".claude/CLAUDE.md"), "utf8");
  const originalSettings = JSON.parse(await readFile(join(home, ".claude/settings.json"), "utf8"));

  const first = await importScope(root, home, "global");
  await init(root, home, "global", first);
  await sync(root, home, ["global"]);
  const second = await importScope(root, home, "global");

  it("import -> sync -> import yields an equal IR", () => {
    expect(withoutSources(second)).toEqual(withoutSources(first));
  });

  it("the second import reads from .agents/, not from the generated file", () => {
    expect(second.instructions.map((i) => i.source)).toEqual([join(home, ".agents/AGENTS.md")]);
  });

  it("instruction semantics survive byte for byte", () => {
    expect(second.instructions[0]?.body).toBe(originalMd);
    expect(second.instructions[0]?.body).toContain("**Reply in Italian**");
    expect(second.instructions[0]?.body).toContain(
      "present a plan and wait for explicit confirmation",
    );
    expect(second.instructions[0]?.body).toContain("Never commit autonomously");
  });

  it("CLAUDE.md is now generated and imports the source", async () => {
    const md = await readFile(join(home, ".claude/CLAUDE.md"), "utf8");
    expect(md).toMatch(
      /^<!-- generated by tenore sync · hash:[0-9a-f]{12} · edit \.agents\/ instead -->\n/,
    );
    expect(md).toContain("@~/.agents/AGENTS.md");
  });

  it("settings keys outside the owned permission paths are untouched", async () => {
    const settings = JSON.parse(await readFile(join(home, ".claude/settings.json"), "utf8"));
    const { permissions, ...rest } = settings;
    const { permissions: originalPermissions, ...originalRest } = originalSettings;
    expect(rest).toEqual(originalRest);
    expect(permissions.additionalDirectories).toEqual(originalPermissions.additionalDirectories);
    expect(permissions.defaultMode).toBe("auto");
  });

  it("a second sync is a byte-for-byte no-op", async () => {
    const files = [".claude/CLAUDE.md", ".claude/settings.json"].map((f) => join(home, f));
    const before = await Promise.all(files.map((f) => readFile(f, "utf8")));
    await sync(root, home, ["global"]);
    expect(await Promise.all(files.map((f) => readFile(f, "utf8")))).toEqual(before);
  });
});

describe("round-trip: .agents -> sync -> import equals the parsed source (fixture basic)", async () => {
  const root = await writeTree({});
  const home = await writeTree({});
  await cp(join(FIXTURES, "basic/repo"), root, { recursive: true });
  await cp(join(FIXTURES, "basic/home"), home, { recursive: true });
  const scopes: Scope[] = ["global", "repo", "local"];
  await sync(root, home, scopes);
  const layers = await parseLayers(root, home);

  it.each(scopes)("%s scope", async (scope) => {
    const layer = layers.find((l) => l.scope === scope);
    const imported = await importScope(root, home, scope);
    expect(imported.instructions).toEqual(layer?.instructions);
    expect(imported.memory).toEqual(layer?.memory);
    expect(imported.policy).toEqual(layer?.policy);
    expect(imported.warnings).toEqual([]);
  });
});

describe("round-trip: policy table", () => {
  const cases: { name: string; policy: string; expected?: object }[] = [
    {
      name: "every capability kind",
      policy: [
        "permissions:",
        "  default: deny",
        "  allow: [{ shell: 'npm run test*' }, { fs.write: 'src/**' }, { mcp: 'gh.*' }]",
        "  ask: [{ shell: 'git push*' }, { mcp: 'gh.create_pr' }]",
        "  deny: [{ fs.read: '.env*' }, { fs.read: '/etc/**' }, { fs.write: '~/.ssh/**' }, { network: none }]",
      ].join("\n"),
    },
    { name: "network restricted", policy: "permissions:\n  ask: [{ network: restricted }]" },
    { name: "shell wildcard", policy: "permissions:\n  allow: [{ shell: '*' }]" },
    {
      name: "raw overrides and remote MCP survive",
      policy: [
        "mcp:",
        "  gh: { command: npx, args: ['-y', 'gh-mcp'], env: { GITHUB_TOKEN: '${env:GITHUB_TOKEN}' } }",
        "overrides:",
        "  claude:",
        "    permissions: { allow: ['WebFetch(domain:docs.example.com)'], defaultMode: plan }",
        "    mcpServers: { remote: { type: http, url: 'https://example.com/mcp' } }",
      ].join("\n"),
    },
    {
      name: "network full is equivalent to unset (documented)",
      policy: "permissions:\n  allow: [{ network: full }, { shell: 'ls*' }]",
      expected: { permissions: { allow: [{ shell: "ls*" }] } },
    },
    {
      name: "network level, not list, carries the meaning (documented)",
      policy: "permissions:\n  allow: [{ network: none }]",
      expected: { permissions: { deny: [{ network: "none" }] } },
    },
  ];

  it.each(cases)("$name", async ({ policy, expected }) => {
    const root = await writeTree({ ".agents/policy.md": `---\n${policy}\n---\n` });
    const home = await writeTree({});
    await sync(root, home, ["repo"]);
    const [, layer] = await parseLayers(root, home);
    const imported = await importScope(root, home, "repo");
    expect(imported.policy).toEqual(expected ?? layer?.policy);
  });
});
