import { createHash } from "node:crypto";

/** First 12 hex chars of sha256: short enough for a header, long enough to detect edits. */
export function shortHash(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex").slice(0, 12);
}

const HEADER =
  /^<!-- generated by tenore sync · hash:([0-9a-f]{12}) · edit \.agents\/ instead -->\n/;

/** Prefixes a Markdown body with the generated-file header; the hash covers the body only. */
export function withHeader(body: string): string {
  return `<!-- generated by tenore sync · hash:${shortHash(body)} · edit .agents/ instead -->\n${body}`;
}

/** Splits a generated Markdown file; `undefined` when the header is missing (hand-written file). */
export function parseHeader(content: string): { hash: string; body: string } | undefined {
  const match = HEADER.exec(content);
  if (!match?.[1]) return undefined;
  return { hash: match[1], body: content.slice(match[0].length) };
}
