import { createHash } from "node:crypto";

/** First 12 hex chars of sha256: short enough for a header, long enough to detect edits. */
export function shortHash(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex").slice(0, 12);
}

/** Comment syntax of the target file: `html` for Markdown, `hash` for TOML/Starlark. */
export type HeaderStyle = "html" | "hash";

const HEADERS: Record<HeaderStyle, RegExp> = {
  html: /^<!-- generated by tenore sync · hash:([0-9a-f]{12}) · edit \.agents\/ instead -->\n/,
  hash: /^# generated by tenore sync · hash:([0-9a-f]{12}) · edit \.agents\/ instead\n/,
};

/** Prefixes a body with the generated-file header; the hash covers the body only. */
export function withHeader(body: string, style: HeaderStyle = "html"): string {
  const text = `generated by tenore sync · hash:${shortHash(body)} · edit .agents/ instead`;
  return style === "html" ? `<!-- ${text} -->\n${body}` : `# ${text}\n${body}`;
}

/** Splits a generated file (either style); `undefined` when the header is missing (hand-written file). */
export function parseHeader(content: string): { hash: string; body: string } | undefined {
  for (const re of Object.values(HEADERS)) {
    const match = re.exec(content);
    if (match?.[1]) return { hash: match[1], body: content.slice(match[0].length) };
  }
  return undefined;
}
