import { isPlainObject } from "../../ir/canonical.ts";
import type { Warning } from "../../ir/diagnostics.ts";
import type { Capability, Ir, NetworkLevel, PermissionLevel } from "../../ir/schema.ts";

/**
 * Opt-in (`overrides.codex.permission_profiles: true`) mapping of fs and
 * network capabilities to a Codex permission profile (beta upstream):
 *
 *   default_permissions = "tenore"
 *   [permissions.tenore]  extends = ":workspace"
 *   [permissions.tenore.filesystem.":workspace_roots"]  "<glob>" = "deny" | "read" | "write"
 *   [permissions.tenore.network]  enabled = false
 *
 * Verified against https://learn.chatgpt.com/docs/permissions (2026-10).
 * Profiles are sandbox rules: a blocked access can still be escalated to an
 * approval prompt under `approval_policy = "on-request"`; with "never" it is refused.
 * Codex ignores profiles when any config layer sets `sandbox_mode`.
 */
export const PROFILE_NAME = "tenore";
export const PROFILE_KEYS = ["default_permissions", `permissions.${PROFILE_NAME}`] as const;

type Access = "deny" | "read" | "write";
const RANK: Record<Access, number> = { deny: 0, read: 1, write: 2 };
const WORKSPACE = ":workspace_roots";

export function profilesEnabled(ir: Ir): boolean {
  return isPlainObject(ir.overrides.codex) && ir.overrides.codex.permission_profiles === true;
}

/**
 * deny fs.read -> "deny"; deny fs.write -> "read"; allow fs.write -> "write";
 * allow fs.read -> "read". Ask has no profile form: it becomes the matching
 * sandbox block ("deny" for reads, "read" for writes), which Codex turns into an
 * escalation prompt. On a collision the most restrictive access wins.
 */
export function codexProfile(
  ir: Ir,
  network: NetworkLevel | undefined,
  warnings: Warning[],
): Record<string, unknown> {
  const roots: Record<string, Access> = {};
  const absolute: Record<string, Access> = {};

  for (const list of ["deny", "ask", "allow"] as const) {
    for (const cap of ir.permissions[list] as Capability[]) {
      if (!("fs.read" in cap) && !("fs.write" in cap)) continue;
      const read = "fs.read" in cap;
      const glob = read ? cap["fs.read"] : cap["fs.write"];
      const access = accessFor(list, read);
      if (list === "ask") {
        warnings.push({
          code: "codex-fs-ask-as-sandbox",
          message: `ask ${read ? "fs.read" : "fs.write"} "${glob}" becomes a sandbox block in the Codex profile; access goes through an escalation prompt`,
        });
      }
      const isAbsolute = glob.startsWith("/") || glob.startsWith("~/");
      const table = isAbsolute ? absolute : roots;
      const key = isAbsolute ? glob : anchoredKey(glob);
      const prev = table[key];
      if (prev === undefined || RANK[access] < RANK[prev]) table[key] = access;
    }
  }

  const profile: Record<string, unknown> = {
    description: "Generated by tenore from .agents/policy.md",
    extends: ":workspace",
  };
  const filesystem: Record<string, unknown> = { ...sorted(absolute) };
  if (Object.keys(roots).length > 0) filesystem[WORKSPACE] = sorted(roots);
  if (Object.keys(filesystem).length > 0) profile.filesystem = filesystem;
  if (network !== undefined) profile.network = { enabled: network === "full" };
  return { default_permissions: PROFILE_NAME, permissions: { [PROFILE_NAME]: profile } };
}

function accessFor(list: PermissionLevel, read: boolean): Access {
  if (list === "allow") return read ? "read" : "write";
  return read ? "deny" : "read";
}

/** IR "any depth" names (no inner `/`) need an explicit `**` under each workspace root. */
function anchoredKey(glob: string): string {
  return glob.replace(/\/+$/, "").includes("/") ? glob : `**/${glob}`;
}

function sorted<T>(record: Record<string, T>): Record<string, T> {
  return Object.fromEntries(
    Object.keys(record)
      .sort()
      .map((k) => [k, record[k] as T]),
  );
}

/**
 * Inverse of {@link codexProfile} for a profile tenore generated. `"read"`
 * means "no writes" under the workspace roots (which are writable by default)
 * and "may read" for an absolute path outside them.
 */
export function profileCapabilities(
  profile: Record<string, unknown>,
):
  | { caps: { list: PermissionLevel; cap: Capability }[]; network: boolean | undefined }
  | undefined {
  const known = new Set(["description", "extends", "filesystem", "network"]);
  if (Object.keys(profile).some((k) => !known.has(k)) || profile.extends !== ":workspace")
    return undefined;

  const caps: { list: PermissionLevel; cap: Capability }[] = [];
  const fs = profile.filesystem ?? {};
  if (!isPlainObject(fs)) return undefined;
  for (const [key, value] of Object.entries(fs)) {
    if (key === WORKSPACE) {
      if (!isPlainObject(value)) return undefined;
      for (const [sub, access] of Object.entries(value)) {
        const glob = sub.startsWith("**/") && !sub.slice(3).includes("/") ? sub.slice(3) : sub;
        if (access === "deny") caps.push({ list: "deny", cap: { "fs.read": glob } });
        else if (access === "read") caps.push({ list: "deny", cap: { "fs.write": glob } });
        else if (access === "write") caps.push({ list: "allow", cap: { "fs.write": glob } });
        else return undefined;
      }
    } else if (key.startsWith("/") || key.startsWith("~/")) {
      if (value === "deny") caps.push({ list: "deny", cap: { "fs.read": key } });
      else if (value === "read") caps.push({ list: "allow", cap: { "fs.read": key } });
      else if (value === "write") caps.push({ list: "allow", cap: { "fs.write": key } });
      else return undefined;
    } else {
      return undefined;
    }
  }

  let network: boolean | undefined;
  if (profile.network !== undefined) {
    if (
      !isPlainObject(profile.network) ||
      Object.keys(profile.network).some((k) => k !== "enabled")
    )
      return undefined;
    if (typeof profile.network.enabled !== "boolean") return undefined;
    network = profile.network.enabled;
  }
  return { caps, network };
}
